# Copyright 2022 David Garcia
# See LICENSE file for licensing details.

options:
  accounts:
    description: |
      Content of the .local/share/juju/accounts.yaml file,
      which includes the relevant information about the accounts.
    type: string
  controllers:
    description: |
      Content of the .local/share/juju/controllers.yaml file,
      which includes the relevant information about the controllers.
    type: string
  public-key:
    description: |
      Juju public key, usually located at ~/.local/share/juju/ssh/juju_id_rsa.pub
    type: string
  lxd-cloud:
    description: |
      Name and credentials of the lxd cloud.
      This cloud will be used by N2VC to deploy LXD Proxy Charms.

      The expected input is the following:
        <lxd-cloud-name>[:<lxd-credential-name>]

        By default, the <lxd-credential-name> will be the same as
        <lxd-cloud-name>.
    type: string
  k8s-cloud:
    description: |
      Name and credentials of the k8s cloud.
      This cloud will be used by N2VC to deploy K8s Proxy Charms.

      The expected input is the following:
        <k8s-cloud-name>[:<k8s-credential-name>]

        By default, the <k8s-credential-name> will be the same as
        <k8s-cloud-name>.
    type: string
  model-configs:
    type: string
    description: |
      Yaml content with all the default model-configs to be sent
      in the relation vca relation.

      Example:
        juju config vca-integrator model-configs='
        agent-metadata-url: <>
        agent-stream: ...
        apt-ftp-proxy:
        apt-http-proxy:
        apt-https-proxy:
        apt-mirror:
        apt-no-proxy:
        automatically-retry-hooks:
        backup-dir:
        cloudinit-userdata:
        container-image-metadata-url:
        container-image-stream:
        container-inherit-properties:
        container-networking-method:
        default-series:
        default-space:
        development:
        disable-network-management:
        egress-subnets:
        enable-os-refresh-update:
        enable-os-upgrade:
        fan-config:
        firewall-mode:
        ftp-proxy:
        http-proxy:
        https-proxy:
        ignore-machine-addresses:
        image-metadata-url:
        image-stream:
        juju-ftp-proxy:
        juju-http-proxy:
        juju-https-proxy:
        juju-no-proxy:
        logforward-enabled:
        logging-config:
        lxd-snap-channel:
        max-action-results-age:
        max-action-results-size:
        max-status-history-age:
        max-status-history-size:
        net-bond-reconfigure-delay:
        no-proxy:
        provisioner-harvest-mode:
        proxy-ssh:
        snap-http-proxy:
        snap-https-proxy:
        snap-store-assertions:
        snap-store-proxy:
        snap-store-proxy-url:
        ssl-hostname-verification:
        test-mode:
        transmit-vendor-metrics:
        update-status-hook-interval:
        '
